### ISSUE TITLE
Kinesis Pipes transfer more RF than they should ("dupe")

### ISSUE THREAD

**Issue by xJon** [JackRaidenPH/BuildCraftRF#3]
I have a setup with an IC2C generator (10 EU/t) and a Flux Generator (converts to RF with 1/8 EU/RF ratio).
Using the Kinesis Pipes and this mod, they transfer much more energy than they should. This does not happen with other RF cables:

https://user-images.githubusercontent.com/8945347/227736037-9a2bab51-68f2-4a23-b26e-90866c2c377f.mp4

**Comment by jackraidenph** [comment]
This is a IC2C bug. BCRF does not change kinesis pipes behavior.

**Comment by xJon** [comment]
If BCRF does not change Kinesis Pipes how do they transfer RF at all?

**Comment by jackraidenph** [comment]
Being honest - that's a nice question. I can replicate the very same setup with BCRF not being present at all:
![image](https://user-images.githubusercontent.com/41832859/227798256-922e86ea-1296-4b1b-8214-e1ba234e7a88.png)

**Comment by jackraidenph** [comment]
Also, just to be sure, are you sure you are not mixing my repo up with
https://github.com/EndangeredNayla/BuildCraft-Fluxified
That is present in Tekkit?

**Comment by xJon** [comment]
> Also, just to be sure, are you sure you are not mixing my repo up with https://github.com/EndangeredNayla/BuildCraft-Fluxified That is present in Tekkit?

Yes, I was testing BCRF as a better alternative :) Unfortunately this issue would be too problematic.
Edit 2: I'm not sure whether this is caused by IC2C alone. I assume BuildCraft Kinesis Pipes only _partially_ support RF and that causes some issues with other mods? I'll keep testing.

Is there any chance BCRF could make proper support for RF Kinesis Pipes? Because with the current feature set of the mod, it is painfully missing (albeit working only with BuildCraft)

**Comment by Speiger** [comment]
@xJon @JackRaidenPH 

this is the code that i use to allow RF Injection into Blocks.
This block works with RF as power storage instead of EU because dealing with conversions is worse to do in RF then in EU.

But yeah this is the Code related to RF.
```java
if(cacheTile.hasCapability(CapabilityEnergy.ENERGY, getFacing().getOpposite()))
{
	IEnergyStorage storage = cacheTile.getCapability(CapabilityEnergy.ENERGY, getFacing().getOpposite());
	if(storage.canReceive())
	{
		int needed = storage.getMaxEnergyStored() - storage.getEnergyStored();
		if(needed > 0)
		{
			energy -= storage.receiveEnergy(Math.min(energy, needed), false);
			getNetwork().updateTileGuiField(this, "energy");
		}
	}
}
```
The block auto outputs.

If you draw Energy this logic applies:
```java
	@Override
	public boolean hasCapability(Capability<?> capability, EnumFacing facing)
	{
		if(capability == CapabilityEnergy.ENERGY)
		{
			return facing == null || facing == getFacing();
		}
		if(Loader.isModLoaded("buildcraftlib") && isMJ(capability))
		{
			return facing == null || facing == getFacing();
		}
		return super.hasCapability(capability, facing);
	}

	@Override
	public <T> T getCapability(Capability<T> capability, EnumFacing facing)
	{
		if(capability == CapabilityEnergy.ENERGY)
		{
			return (T)this;
		}
		if(Loader.isModLoaded("buildcraftlib") && isMJ(capability))
		{
			return (T)this;
		}
		return super.getCapability(capability, facing);
	}
	
	@Override
	public int receiveEnergy(int maxReceive, boolean simulate)
	{
		return 0;
	}

	@Override
	public int extractEnergy(int maxExtract, boolean simulate)
	{
		if(maxExtract > energy)
		{
			maxExtract = energy;
		}
		if(!simulate)
		{
			energy -= maxExtract;
		}
		return maxExtract;
	}

	@Override
	public int getEnergyStored()
	{
		return energy;
	}

	@Override
	public int getMaxEnergyStored()
	{
		return maxEnergy;
	}
```

If there is a mistake tell me :)

**Comment by jackraidenph** [comment]
The issue is connected to how BC kinesis pipes interact with capability-exposing blocks. I'm not sure what exactly is the bug, I'll look into BC code later, but if Flux Generator is connected to a block directly(not via pipes) - the bug is not present. 

The problem is, BC code for pipes is kinda questionable and, it seems, is written with just BC in mind(even though the API), which is also a reason why I don't really want to touch them.

**Comment by jackraidenph** [comment]
@Speiger Also, please note the fact, that BC calculates it's energy not in Minecraft Joules, but in Micro Joules, which is 10^-6 times 1 Minecraft Joule. That's why I do the conversions in my mixin:
https://github.com/JackRaidenPH/BuildCraftRF/blob/master/src/main/java/dev/jackraidenph/bcrf/mixins/MjBatteryMixin.java

**Comment by jackraidenph** [comment]
In further investigation, I believe the conversion lack might be the issue. The bug IS in fact present even if Flux Generator is connected directly to a BC machine, but only if BCRF is not present. Because if BCRF is present, BC machines act primarily as a FE storage, dealing fluently with Flux Generator. If BCRF is not present, BC machines act normally, as a MJ Storage, producing the bug.

**Comment by Speiger** [comment]
@JackRaidenPH 
The system you speak about is the "RF" System. Nothing to do with MJ.

The MJ System uses this:
```java
	public boolean handleBC(TileEntity tile)
	{
		if(tile.hasCapability(MjAPI.CAP_RECEIVER, getFacing().getOpposite()))
		{
			IMjReceiver receiver = cacheTile.getCapability(MjAPI.CAP_RECEIVER, getFacing().getOpposite());
			if(receiver.canReceive() && receiver.canConnect(this))
			{
				int needed = (int)(receiver.getPowerRequested() / MjAPI.ONE_MINECRAFT_JOULE);
				if(needed > 0)
				{
					energy -= (needed - ((receiver.receivePower((long)(needed * MjAPI.ONE_MINECRAFT_JOULE * 2.5D), false) / MjAPI.ONE_MINECRAFT_JOULE) / 2.5D));
					getNetwork().updateTileGuiField(this, "energy");
				}
			}
			return true;
		}
		return false;
	}
```

But yeah i think i found the issue. 
I am treating RF to MJ as EU to MJ which is the mistake.
Thank you ill address that xD

**Comment by jackraidenph** [comment]
> The system you speak about is the "RF" System. Nothing to do with MJ.

Oh well, I guess I misunderstood the code sample then, sorry.

Regarding the later code sample with MJ, yeah, I can clearly see the issue. You don't check for over-/underflow.

The issue matches the observed behavior in my test world:
If HV Flux Generator is placed next to a quarry, the following happens:
1) In 1 tick, the quarry receives 60k MJ, which matches the **[needed * 2.5]** piece, where needed is full quarry capacity
(24k MJ)
2) The underflow is not checked, so HVFG is immediately drawn 24k RF, which matches **[received / 10^6 / 2.5]** piece, where **received** is 24*10^6 mJ

Otherwise everything seems fine. (Unless Flux Generator is meant to have maximum output rate, which is also not checked)

**Comment by jackraidenph** [comment]
@xJon 
Regarding the kinesis pipes support.
Deeply sorry for being unfamiliar with Tekkit2 set of mods, but are there any mods that add RF pipes? Because if so, MJ engines will properly connect to them and generate RF(as shown on the second screenshot on CF page). The behavior must persist on most pipes implementations.

So taking 4 possible scenarios:
1) MJ to MJ -> Native BC
2) RF to RF -> Native Forge
3) RF -> MJ -> BC/RF generators -> RF cables -> MJ machine
4) MJ -> RF -> BC generators -> RF cables -> RF machine

**Comment by Speiger** [comment]
> Otherwise everything seems fine. (Unless Flux Generator is meant to have maximum output rate, which is also not checked)


Nah the issue is solved with this implementation.
Since 1MJ is 10RF i can simply change the code to this and its fixed.
```java
	public boolean handleBC(TileEntity tile)
	{
		if(tile.hasCapability(MjAPI.CAP_RECEIVER, getFacing().getOpposite()))
		{
			IMjReceiver receiver = cacheTile.getCapability(MjAPI.CAP_RECEIVER, getFacing().getOpposite());
			if(receiver.canReceive() && receiver.canConnect(this))
			{
				int toTransfer = (int)Math.min(receiver.getPowerRequested() / MjAPI.ONE_MINECRAFT_JOULE, energy / 10);
				if(toTransfer > 0)
				{
					energy -= (toTransfer - ((receiver.receivePower((long)(toTransfer * MjAPI.ONE_MINECRAFT_JOULE), false) / MjAPI.ONE_MINECRAFT_JOULE) * 10D));
					getNetwork().updateTileGuiField(this, "energy");
				}
			}
			return true;
		}
		return false;
	}
```

Though the next patch isn't on queue for another few weeks but this is what i am going to do.
@JackRaidenPH

**Comment by xJon** [comment]
@JackRaidenPH Yes there are alternative RF cables, yet for nostalgic reasons some players prefer to use Kinesis Pipes. Currently in the modpack they work only within Buildcraft, and it is advised for players to use other RF cables for any mod interaction that's not only within Buildcraft (I originally thought there's a chance using this mod Kinesis Pipes could be used between Buildcraft and other mods to transfer RF so there'd be less confusion).
If you don't want to rework Kinesis Pipes that's perfectly fine, I just thought it's worth asking since it'd be neat :)
